/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import controller.EventoCTRL;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Evento;
import model.Usuario;
import view.MenuPrincipal;

/**
 *
 * @author natan
 */
public class DiaCalendario extends javax.swing.JPanel {

    /**
     * Creates new form DiaCalendario
     */
    
    private boolean pressedMouse;
    
    private int dia;
    private int mes;
    private int ano;
    private MenuPrincipal classePai;
    private ArrayList <Evento> eventos;
    Usuario usuarioLogado;
    
    public DiaCalendario() {
        initComponents();
        this.setVisible(true);
    }
    
    /** Informa o componente qual a classe do menu a ser usada e fornece os dados do usuário logado */
    public void setClassePai(MenuPrincipal menu, Usuario usuario, JPanel panelPaiDia){
        classePai = menu;
        usuarioLogado = usuario;
        this.setVisible(true);
        this.setLocation(0, 0);
        this.setSize(panelPaiDia.getSize());
        panelPaiDia.add(this);
    }
    
    public int getAno(){
        return this.ano;
    }
    
    public int getMes(){
        return this.mes;
    }
    
    public int getDia(){
        return this.dia;
    }
    
    public void setData(int dia, int mes, int ano){
        
        this.dia = dia;
        this.mes = mes;
        this.ano = ano;
        
        if(dia!=0){
            lblNumeroDia.setText(Integer.toString(dia));
        }else{
            lblNumeroDia.setText("");
        }
        
        String dataStr = this.ano +"-"+ this.mes +"-"+ this.dia;

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date data = null;
        try {
            data = new java.sql.Date(format.parse(dataStr).getTime());
        } catch (ParseException e) { }

        EventoCTRL controleEvento = new EventoCTRL();
        this.eventos = controleEvento.listarCalendario(eventos, usuarioLogado.getLogin(), data);
        panelEventosDia.removeAll();
        panelEventosDia.repaint();

        int posY = 0;
        for(int i=0;i<eventos.size();i++){
            JLabel evento = new JLabel();
            evento.setSize(115, 15);
            evento.setHorizontalAlignment(JLabel.CENTER);
            evento.setFont(new Font("Open Sans", 0, 12));
            evento.setText(eventos.get(i).getDescricao());
            evento.setLocation(0, posY);
            evento.setText(eventos.get(i).getDescricao());
            posY += 15;

            String[] cor = eventos.get(i).getCor().substring(1,eventos.get(i).getCor().length()-1).split(",");
            evento.setBackground(new Color(Integer.parseInt(cor[0]),Integer.parseInt(cor[1]),Integer.parseInt(cor[2])));
            evento.setOpaque(true);

            if(eventos.get(i).getContraste()==1){
                evento.setForeground(new Color(10,24,39));
            }else{
                evento.setForeground(new Color(204,217,206));
            }

            evento.setVisible(true);
            panelEventosDia.add(evento);
            panelEventosDia.repaint();
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEventosDia = new javax.swing.JPanel();
        lblNumeroDia = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(252, 255, 245));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        panelEventosDia.setBackground(new java.awt.Color(252, 255, 245));
        panelEventosDia.setForeground(new java.awt.Color(252, 255, 245));

        javax.swing.GroupLayout panelEventosDiaLayout = new javax.swing.GroupLayout(panelEventosDia);
        panelEventosDia.setLayout(panelEventosDiaLayout);
        panelEventosDiaLayout.setHorizontalGroup(
            panelEventosDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );
        panelEventosDiaLayout.setVerticalGroup(
            panelEventosDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        lblNumeroDia.setBackground(new java.awt.Color(10, 24, 39));
        lblNumeroDia.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lblNumeroDia.setForeground(new java.awt.Color(252, 255, 245));
        lblNumeroDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroDia.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEventosDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNumeroDia, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblNumeroDia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelEventosDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pressedMouse = false;
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        pressedMouse = true;
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        if(pressedMouse){
            classePai.atualizarDiaDestaqueCalendario(this.dia, eventos);
        }
    }//GEN-LAST:event_jPanel1MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumeroDia;
    private javax.swing.JPanel panelEventosDia;
    // End of variables declaration//GEN-END:variables
}
