/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import java.awt.Cursor;
import javax.swing.JLabel;
import model.Categoria;
import view.MenuPrincipal;

/**
 *
 * @author natan
 */
public class ListaCategoriaEvento extends JLabel {

    /**
     * Creates new form ListaCategoriaEvento
     */
    
    private MenuPrincipal classePai;
    private Categoria categoria;
    
    private boolean pressedMouse;
    
    public ListaCategoriaEvento() {
        initComponents();
    }
    
    /** Define o menu para o qual os dados serão enviados com o clique */
    public void getClassePai(MenuPrincipal menu){
        classePai = menu;
    }
    
    public void setCategoria(Categoria categoria){
        this.categoria = categoria;
    }
    
    public Categoria getCategoria(){
        return this.categoria;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pressedMouse = false;
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        pressedMouse = true;
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if(pressedMouse){
            classePai.atualizarDadosListagemCategorias(categoria);
        }
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
