/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import java.awt.Cursor;

/**
 *
 * @author natan
 */
public class PanelImportancia extends javax.swing.JPanel {

    /**
     * Creates new form PanelImportancia
     */
    
    private int importancia = 0;
    
    private boolean pressedMouseEstrela1;
    private boolean pressedMouseEstrela2;
    private boolean pressedMouseEstrela3;
    
    String dirEstrela = "/imagens/EstrelaPreto.png";
    String dirEstrelaVazia = "/imagens/EstrelaVaziaPreto.png";
    
    public PanelImportancia() {
        initComponents();
    }
    
    public int getImportancia(){
        return importancia;
    }
    
    public void setImportancia(int importancia){
        this.importancia = importancia;
        switch(importancia){
            case 0:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
                break;
            case 1:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaPreto.png")));
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
                break;
            case 2:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaPreto.png")));
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaPreto.png")));
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
                break;
            case 3:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaPreto.png")));
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaPreto.png")));
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaPreto.png")));
        }
    }
    
    public void clearStars(){
        this.importancia=0;
        estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
        estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
        estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EstrelaVaziaPreto.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estrela1 = new javax.swing.JLabel();
        estrela2 = new javax.swing.JLabel();
        estrela3 = new javax.swing.JLabel();

        setOpaque(false);

        estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EstrelaVaziaPreto.png"))); // NOI18N
        estrela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrela1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrela1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estrela1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estrela1MouseReleased(evt);
            }
        });

        estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EstrelaVaziaPreto.png"))); // NOI18N
        estrela2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrela2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrela2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estrela2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estrela2MouseReleased(evt);
            }
        });

        estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/EstrelaVaziaPreto.png"))); // NOI18N
        estrela3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrela3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrela3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estrela3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                estrela3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(estrela1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(estrela2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(estrela3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estrela1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(estrela3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(estrela2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void estrela1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela1MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrela)));
    }//GEN-LAST:event_estrela1MouseEntered

    private void estrela1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela1MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pressedMouseEstrela1 = false;
        switch(importancia){
            case 0:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
            break;
        }
    }//GEN-LAST:event_estrela1MouseExited

    private void estrela1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela1MousePressed
        pressedMouseEstrela1 = true;
    }//GEN-LAST:event_estrela1MousePressed

    private void estrela1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela1MouseReleased
        if(pressedMouseEstrela1){
            importancia = 1;
            estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
            estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
        }
    }//GEN-LAST:event_estrela1MouseReleased

    private void estrela2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela2MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrela)));
        estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrela)));
    }//GEN-LAST:event_estrela2MouseEntered

    private void estrela2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela2MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pressedMouseEstrela2 = false;
        switch(importancia){
            case 0:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
            break;
            case 1:
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
        }
    }//GEN-LAST:event_estrela2MouseExited

    private void estrela2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela2MousePressed
        pressedMouseEstrela2 = true;
    }//GEN-LAST:event_estrela2MousePressed

    private void estrela2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela2MouseReleased
        if(pressedMouseEstrela2){
            importancia = 2;
            estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
        }
    }//GEN-LAST:event_estrela2MouseReleased

    private void estrela3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela3MouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrela)));
        estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrela)));
        estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrela)));
    }//GEN-LAST:event_estrela3MouseEntered

    private void estrela3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela3MouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        pressedMouseEstrela3 = false;
        switch(importancia){
            case 0:
                estrela1.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
            break;
            case 1:
                estrela2.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
            break;
            case 2:
                estrela3.setIcon(new javax.swing.ImageIcon(getClass().getResource(dirEstrelaVazia)));
        }
    }//GEN-LAST:event_estrela3MouseExited

    private void estrela3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela3MousePressed
        pressedMouseEstrela3 = true;
    }//GEN-LAST:event_estrela3MousePressed

    private void estrela3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrela3MouseReleased
       if(pressedMouseEstrela3){
           importancia = 3;
       }
    }//GEN-LAST:event_estrela3MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estrela1;
    private javax.swing.JLabel estrela2;
    private javax.swing.JLabel estrela3;
    // End of variables declaration//GEN-END:variables
}
